config/routes.rb
PassTheSugar::Application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  root to: 'accounts#index'

  resources :sessions, only: [ :new, :create, :destroy ]

  get 'help', :to => 'dashboard#help'
  get 'graphs/:account_id/diabetics/:id', :to => 'graphs#show', :as => 'show_graph'
  get 'dashboard/get', :to => 'dashboard#get', :as => 'get_submenu'
  get 'diabetics/:id/dashboard', :to => 'dashboard#diabetic', :as => 'diabetic_dashboard'
  get 'dashboard', :to => 'dashboard#show', :as => 'dashboard'

  put 'accounts/changepassword', :to => 'accounts#change_password'
  resources :accounts do
    resources :diabetics, except: [ :index, :delete ]
  end

  resources :diabetics, only: [] do
    resources :records, :preferences, :doctors, except: [:delete]
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :load_diabetic, only: [:diabetic]
  def get
    choices = params[:menu_choice].split(':')
    @diabetic = Diabetic.find(choices[1].split('--')[1]) if choices[0] == 'Diabetic'
    render :partial => 'dashboard/menu', :locals => {
                                                    diabetic: @diabetic,
                                                    account: current_account
                                                  }
  end

  def show
    @diabetics = current_account.diabetics
    render  :partial => 'accounts/show',
            :locals => {
              account: current_account,
              diabetics: @diabetics,
              menu_options: format_menu(@diabetics, current_account)
            }
  end

  def diabetic
    render :partial => "dashboard/diabetic", :locals => {
                                                        diabetic: @diabetic,
                                                        account: current_account,
                                                        prefPath: getPreferencePath,
                                                        doctorPath: getDoctorPath
                                                      }
  end


  def help
    render partial: 'shared/help'
  end

  private
  def load_diabetic
    @diabetic = Diabetic.find(params[:id])
  end

  def getPreferencePath
    if !!@diabetic.preference
      edit_diabetic_preference_path(@diabetic.id, @diabetic.preference.id)
    else
      new_diabetic_preference_path(@diabetic.id)
    end
  end

  def getDoctorPath
    if !!@diabetic.doctor
      edit_diabetic_doctor_path(@diabetic, @diabetic.doctor)
    else
      new_diabetic_doctor_path(@diabetic)
    end
  end


end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def format_menu(diabetics, account)
    result = ['Pick a User or account']
    result += diabetics.map {|diabetic| "Diabetic: #{diabetic.name} -- #{diabetic.id} "}
    result << "Account: #{current_account.username}"
    result
  end
end

app/views/dashboard/_diabetic.html.erb
<%= button_tag 'Add Preferences', data: { type:'edit-diabetic-button', url: prefPath, style: 'edit-preferences' }, remote: true %>
<%= button_tag 'Edit User Info', data: { type:'edit-diabetic-button', url: edit_account_diabetic_path(account, diabetic), style: 'edit-user-info' }, remote: true %>
<%= button_tag 'Edit Doctor Info', data: { type:'edit-diabetic-button', url: doctorPath, style: 'edit-doctor-info' }, remote: true %>
<script>
var title = "Edit <%= diabetic.name %>'s info"
var leftButton = {
  type: 'cancel',
  text: 'Back'
}
var rightButton = {
  type: 'none',
  text: 'Save'
}
</script>

app/views/dashboard/_menu.html.erb
<% if diabetic %>
  <%= button_tag "Add record for: #{diabetic.name}", data: { type: 'dashboard-button', url: new_diabetic_record_path(diabetic), style: 'add-record' }, remote: true %><br>
  <%= button_tag "View #{diabetic.name}'s records", data: { type: 'dashboard-button', url: diabetic_records_path(diabetic), style: 'view-record' }, remote: true %><br>
  <%= button_tag "Edit #{diabetic.name}'s info", data: { type: 'dashboard-button', url: diabetic_dashboard_path(diabetic.id), style: 'edit-diabetic' }, remote: true %><br>
<% else %>
  <%= button_tag 'Add a Diabetic', data: { type: 'dashboard-button', url: new_account_diabetic_path(account), style: 'add-diabetic' }, remote: true %><br>
  <%= button_tag 'Edit the account', data: { type: 'dashboard-button', url: edit_account_path(account), style: 'edit-account' }, remote: true %><br>
<% end %>

app/views/dashboard/_show.html.erb
<form action = "menu", method ="get", data-remote='true' >
  <%= select_tag "menu_choice", options_for_select(menu_options) %>
   <input type="hidden" name="account_id" value='<%= account.id  %>' >
</form>
<div id='submenu'></div>

<!-- <div> <%= button_to "Logout", session_path(account.id), :method => :delete %></div> -->


<script>
var title = "<%= account.username.capitalize %>'s Dashboard"
var leftButton = {
  type: 'logout',
  text: 'Logout'
}
var rightButton = {
  type: 'help',
  text: 'Help'
}

var userid = <%= account.id %>


window.onload = function(){
$('body').trigger('login', userid)
}
</script>