config/routes.rb
PassTheSugar::Application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  root to: 'accounts#index'

  resources :sessions, only: [ :new, :create, :destroy ]

  get 'help', :to => 'dashboard#help'
  get 'graphs/:account_id/diabetics/:id', :to => 'graphs#show', :as => 'show_graph'
  get 'dashboard/get', :to => 'dashboard#get', :as => 'get_submenu'
  get 'diabetics/:id/dashboard', :to => 'dashboard#diabetic', :as => 'diabetic_dashboard'
  get 'dashboard', :to => 'dashboard#show', :as => 'dashboard'

  put 'accounts/changepassword', :to => 'accounts#change_password'
  resources :accounts do
    resources :diabetics, except: [ :index, :delete ]
  end

  resources :diabetics, only: [] do
    resources :records, :preferences, :doctors, except: [:delete]
  end

end

app/models/record.rb
class Record < ActiveRecord::Base
  TIME_LENIENCY = 600
  attr_accessible :weight, :glucose, :taken_at, :comment
  belongs_to :diabetic

  validate :inclusion_of_weight_and_or_glucose
  validate :taken_date_cannot_be_in_the_future
  validates_presence_of :taken_at
  validates_numericality_of :glucose, :weight



  def inclusion_of_weight_and_or_glucose
    unless (self.weight.present? || self.glucose.present?)
      errors.add(:weight, "Must include either weight or glucose")
      errors.add(:glucose, "Must include either weight or glucose")
    end
  end

  def taken_date_cannot_be_in_the_future
    if taken_at.present? && taken_at > (Time.now + TIME_LENIENCY)
      errors.add(:taken_at, "Date taken cannot be in the future")
    end
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController

  before_filter :redirect_if_logged_out, :load_diabetic
  before_filter :load_record, :except => [:index, :new, :create]

  def index
    respond_to do |format|
      format.html do
        render :partial => 'records/index', locals: { records: @diabetic.records, diabetic: @diabetic, account: current_account }
      end
      format.pdf do
        @data = @diabetic.get_data_for_pdf
        pdf = RecordDataPdf.new(@data, @diabetic)
        send_data pdf.render, filename: "#{@diabetic.name}_#{Time.now.strftime("%Y-%m-%d")}", type: "application/pdf"
      end
    end
  end

  def show
    render partial: "records/show", locals: {record: @record, diabetic: @diabetic}
  end

  def new
    @record = Record.new
    render partial: 'records/new', locals: {record: @record, diabetic: @diabetic}
  end

  def create
    @record = @diabetic.records.build(params[:record])
    if @record.save
      ok = true
      path = dashboard_path
    end
    render_json(!!ok, path, @record.errors.full_messages)
  end

  def edit
    render partial: 'records/edit', locals: {record: @record, diabetic: @diabetic}
  end

  def update # Unused
    @record.assign_attributes(params[:record])
    if @record.save
      path = dashboard_path
      ok = true
    end
    render_json(!!ok, path, @record.errors.full_messages)
  end

  def destroy
    @record.destroy
    ok = true
    render_json(!!ok, dashboard_path, @record.errors.full_messages)
  end

  private

  def load_diabetic
    @diabetic = Diabetic.find(params[:diabetic_id])
  end

  def load_record
    @record = Record.find(params[:id])
  end

end

app/views/records/_edit.html.erb
<%= render :partial => 'records/form', locals: { record: record, diabetic: diabetic } %>
<script>
var title = 'Edit a record'
var leftButton = {
  type: 'cancel',
  text: 'Cancel'
}
var rightButton = {
  type: 'submit',
  text: 'Save'
}
</script>

app/views/records/_form.html.erb
<%= form_for ([diabetic,record]), remote: true do |f| %>
  <%= f.label :weight %><br>
  <%= f.text_field :weight %><br>
  <%= f.label :glucose %><br>
  <%= f.text_field :glucose %><br>
  <%= f.label :comment %><br>
  <%= f.text_area :comment %><br>
  <%= f.label :reading_taken_on %><br>
  <div class="enter-record-date">
    <%= f.datetime_select :taken_at, ampm: true, minute_step: 5 %>
  </div>
<% end %>

app/views/records/_index.html.erb
<div id="records-summary">
  <h3> Here are your most recent records </h3>
  <% records.each_with_index do |record, index| %>
    <p><%= button_tag 'Edit', data: { type: 'edit-record-button', url: edit_diabetic_record_path(diabetic, record), style: '' }, remote: true %>
    <%= "#{index+1}" %> --
    <%= render partial: 'records/show', locals: {record: record} %></p>
  <% end  %>
</div>
<div id="records-graph" data-url='<%= show_graph_path(account,diabetic) %>'>
  <%= render :partial => 'graphs/show' %>
</div>

<script>
var title = "<%= diabetic.name %>'s records"
var leftButton = {
  type: 'cancel',
  text: 'Back'
}
var rightButton = {
  type: 'records-toggle',
  text: 'Records'
}
$('#records-graph').trigger('getGraph')
</script>

app/views/records/_new.html.erb
<%= render :partial => 'records/form', locals: { record: record, diabetic: diabetic } %>
<script>
var title = 'Add a record'
var leftButton = {
  type: 'cancel',
  text: 'Cancel'
}
var rightButton = {
  type: 'submit',
  text: 'Add'
}
</script>

app/views/records/_show.html.erb
  <span>
    Date: <%= record.taken_at.localtime.strftime("%m/%d %I:%M %p") %>

    Weight: <%=  record.weight if record.weight.present? %>

    Glucose: <%=  record.glucose if record.glucose.present? %>

    Comments: <%=  record.comment if record.comment.present? %>

  </span>