config/routes.rb
PassTheSugar::Application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  root to: 'accounts#index'

  resources :sessions, only: [ :new, :create, :destroy ]

  get 'help', :to => 'dashboard#help'
  get 'graphs/:account_id/diabetics/:id', :to => 'graphs#show', :as => 'show_graph'
  get 'dashboard/get', :to => 'dashboard#get', :as => 'get_submenu'
  get 'diabetics/:id/dashboard', :to => 'dashboard#diabetic', :as => 'diabetic_dashboard'
  get 'dashboard', :to => 'dashboard#show', :as => 'dashboard'

  put 'accounts/changepassword', :to => 'accounts#change_password'
  resources :accounts do
    resources :diabetics, except: [ :index, :delete ]
  end

  resources :diabetics, only: [] do
    resources :records, :preferences, :doctors, except: [:delete]
  end

end

app/models/preference.rb
class Preference < ActiveRecord::Base

  attr_accessible :reminders, :frequency
  belongs_to :diabetic
  validates_numericality_of :frequency, :allow_nil => true, :greater_than_or_equal_to => 0

end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController
  before_filter :load_diabetic
  before_filter :load_preference, :except => [ :new, :create ]
  before_filter :find_or_create_preference, :only => [ :create ]

  def new
    @preference = Preference.new
    render :partial => 'preferences/new', locals: {
                                                          diabetic: @diabetic,
                                                          preference: @preference
                                                        }
  end

  def create
    if @preference.save
      @diabetic.save
      ok = true
      path = dashboard_path
    end
    render_json(!!ok, path, alert)
  end

  def show
    render :partial => 'preferences/show', locals: {
                          diabetic: @diabetic,
                          preference: @preference
                        }
  end

  def edit
    render :partial => 'preferences/edit', locals: {
                                                          title: "Modify a doctor",
                                                          diabetic: @diabetic,
                                                          preference: @preference
                                                        }
  end

  def update
    if @preference.update_attributes(params[:preference])
      ok = true
      path = dashboard_path
    end
    render_json(!!ok, path, @preference.errors.full_messages)

  end

  private

  def load_diabetic
    @diabetic = Diabetic.find(params[:diabetic_id])
  end

  def load_preference
    @preference = @diabetic.preference
  end

  def find_or_create_preference
    if @diabetic.preference
      @preference = @diabetic.preference
    else
      @preference = Preference.new(params[:preference])
    end
    @diabetic.preference = @preference
  end
end

app/views/preferences/_edit.html.erb
<%= render :partial => 'preferences/form', :locals => { diabetic: diabetic, preference: preference } %>
<script>
var title = "Edit <%= diabetic.name %>'s preferences"
var leftButton = {
  type: 'cancel',
  text: 'Cancel'
}
var rightButton = {
  type: 'submit',
  text: 'Save'
}
</script>

app/views/preferences/_form.html.erb
<%= form_for [diabetic, preference], remote: true do |f| %>
  <br>
  <%= f.label :reminders %><br><br>
  <%= f.label :reminders, "Yes", :value => "true" %>
  <%= f.radio_button :reminders, true, :checked => true %>
  <%= f.label :reminders, "No", :value => "false" %>
  <%= f.radio_button :reminders, false %><br><br>
  <br><br>
  <%= f.label :frequency %><br>
  <%= f.select :frequency, (1..3) %><br><br>
<% end %>

app/views/preferences/_new.html.erb
<%= render :partial => 'preferences/form', :locals => { diabetic: diabetic, preference: preference } %>
<script>
var title = "Add <%= diabetic.name %>'s preferences"
var leftButton = {
  type: 'cancel',
  text: 'Cancel'
}
var rightButton = {
  type: 'submit',
  text: 'Save'
}
</script>

app/views/preferences/_show.html.erb
<h2>Hi, this is the show Preference page</h2>

  <h3>Name</h3>
  <%= @diabetic.name %><br>
  <h3>Reminder</h3>
  <%= @preference.reminders ? "Yes" : "No" %><br>
  <h3>Frequency</h3>
  <%= @preference.frequency %><br>

 <span><%= link_to 'Edit', edit_diabetic_preference_path(@preference) %></span>