config/routes.rb
PassTheSugar::Application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  root to: 'accounts#index'

  resources :sessions, only: [ :new, :create, :destroy ]

  get 'help', :to => 'dashboard#help'
  get 'graphs/:account_id/diabetics/:id', :to => 'graphs#show', :as => 'show_graph'
  get 'dashboard/get', :to => 'dashboard#get', :as => 'get_submenu'
  get 'diabetics/:id/dashboard', :to => 'dashboard#diabetic', :as => 'diabetic_dashboard'
  get 'dashboard', :to => 'dashboard#show', :as => 'dashboard'

  put 'accounts/changepassword', :to => 'accounts#change_password'
  resources :accounts do
    resources :diabetics, except: [ :index, :delete ]
  end

  resources :diabetics, only: [] do
    resources :records, :preferences, :doctors, except: [:delete]
  end

end

app/models/account.rb
class Account < ActiveRecord::Base

  has_many :diabetics

  has_secure_password
  attr_accessible :username, :email, :password, :password_confirmation

  after_validation { self.errors.messages.delete(:password_digest) }

  validates_uniqueness_of :email, :username
  validates_presence_of :username, :email
  validates_length_of :password, :within => 5..40
  validates_format_of :email, :with => /^\w+[\.\w\-]*@\w+\.\w{2,5}$/

  validates_presence_of :password,
                        :message => Proc.new { |error, attributes|
                          "#{attributes[:value]} can't be blank."
                        }

  def confirmed?(params)
    params[:account][:password_confirmation] == params[:account][:new_password]
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
    before_filter :redirect_if_logged_in,  :only => [:new, :index]
    before_filter :redirect_if_logged_out,  :except => [:new, :create, :index]
    before_filter :redirect_unless_authorized, :only => [:show, :menu]

  def index
  end

  def show
    @diabetics = current_account.diabetics
    render  'accounts/show',
            :locals => {
              account: current_account,
              diabetics: @diabetics,
              menu_options: format_menu(@diabetics, current_account)
            }
  end

  def new
    render  :partial => 'accounts/new',
            :locals => {
              account: Account.new
            }
  end

  def create
    account = Account.new(params['account'])
    if account.save
      ok = true
      login account
      path = new_account_diabetic_path(account.id)
    else
      path = new_account_path
    end
    render_json(!!ok, path, account.errors.full_messages)
  end

  def edit
    render  :partial => 'accounts/edit',
            :locals => {
              account: current_account
            }
  end

  def change_password
    if current_account.authenticate(params[:password])
      current_account.password = params[:new_password]
      current_account.password_confirmation = params[:password_confirmation]
      if current_account.save
        ok = true
        path = account_path(current_account)
      end
    end
    render_json(!!ok, path, current_account.errors.full_messages)
  end

  def update
    if current_account.authenticate(params[:account][:password])
      ok = true
      current_account.update_attributes(params[:account])
      path = dashboard_path
    else
      notice = ['Invalid Password']
      path = edit_account_path(current_account)
    end
    render_json(!!ok, path, notice)
  end

  private

  def redirect_unless_authorized
    redirect_to root_path unless current_account.id == params[:id].to_i
  end
end

app/views/accounts/_edit.html.erb
<% if flash[:error] %>
  <% flash[:error].each do |error| %>
  <%= error %>
  <% end %>
<% end %>

<div class="edit_account">
<%= form_for account, remote: true do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
<% end %>
</div>

<script>
var title = 'Edit my account'
var leftButton = {
  type: 'cancel',
  text: 'Cancel'
}
var rightButton = {
  type: 'submit',
  text: 'Save'
}
</script>

app/views/accounts/_edit_password.html.erb
<div class="edit_password">
<%= form_for account, url: accounts_changepassword_path do |f| %>
  <%= hidden_field(:account, :id) %>
  <%= label_tag :new_password, "New Password" %>
  <%= password_field_tag :new_password %>
  <%= label_tag :password_confirmation , 'Password Confirmation'%>
  <%= password_field_tag :password_confirmation %>
  <%= label_tag :password, "Current Password" %>
  <%= password_field_tag :password %>
<% end %>
</div>

<script>
var title = 'Change my password'
var leftButton = {
  type: 'cancel',
  text: 'Cancel'
}
var rightButton = {
  type: 'submit',
  text: 'Save'
}
</script>

app/views/accounts/_new.html.erb
<div class="container">
<% if flash[:error] %>
  <% flash[:error].each do |error| %>
    <%= error %><br>
    <% end %>
  <% end %>

<div id="cancel"> <%= link_to "Home", :back, :style =>
                                                      "color:#E80000;
                                                      font-family:'Orbitron', sans-serif;
                                                        text-decoration:none;
                                                        font-size: 175%;
                                                        margin-left:1100px;
                                                        margin-top:-120px;
                                                        position:fixed;

                                                      " %></div>

<div class="sign_up">
<div class = "opaque">
<br><span id="signup_title">Sign Up</span><br><br>
<%= form_for account, id: 'account-signup', remote: true do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation , 'Password Confirmation'%>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Sign Up" , :style =>
                            "height: 35px;
                            color:white;
                            width:278px;
                            border:1px solid black;
                            font-family:'Orbitron', sans-serif;
                            border-radius: 5px;
                            background-color: #E80000;
                            margin-left:202px" %>
<% end %>
<br><br><br><br>
</div>
</div>




<!--

<script>
var title = ''
var leftButton = {
  type: 'cancel',
  text: 'Cancel'
}
var rightButton = {
  type: 'submit',
  text: 'Sign up'
}
</script>
 -->

app/views/accounts/_show.html.erb
<%= render :partial => 'dashboard/show', :locals => { account: account, diabetics: diabetics, menu_options: menu_options } %>

app/views/accounts/index.html.erb
<div class="login_form">
<%= form_tag sessions_path, id: 'account-login', remote: true do %>
    <%= text_field_tag :username, '', :placeholder => "Username" %>
    <%= password_field_tag :password,'', :placeholder => "Password" %>
    <%= button_tag "Log In" , :class => "submit", data: {type: 'submit'} %>
<% end %>

</div>

<div class = "signup_form">
  <span id="member">Not a Member?</span>
<%= button_tag "Sign Up", :class => "signup", :data => { type: 'signup', url: new_account_path}, :remote => true %>
</div>
<br><br>

<div id="logo">
  <span id="pass">Pass</span> <span id="the">the</span> <span id= "sugar">Sugar</span>
</div>
<br><br>





<script>
var title = ''
var leftButton = {
  type: 'none'
}
var rightButton = {

  type: 'none'
}
</script>

app/views/accounts/show.html.erb
<%= render :partial => 'dashboard/show', :locals => { account: account, diabetics: diabetics, menu_options: menu_options } %>